@host=https://localhost:7264
@hostId=4d775933-172d-422d-a2e2-3b13d86496c7
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ODFmNThhZC1lN2NlLTQxOGQtOGRjOS0yMGZkYmM2MjMzNmIiLCJnaXZlbl9uYW1lIjoiQWxhIiwiZmFtaWx5X25hbWUiOiJLb3dhbHNrYSIsImp0aSI6IjQ1MjI2NDJlLWQ3ODgtNDViOS1hNGQ4LWQyOWM0ZWY0YTQyNCIsImV4cCI6MTY4OTU2NTQ5MywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.NSvovkOd9rXvJYIwNSf_5jLdWbeb_aAmBYF-NlQMOig

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"ala",
    "Description":"desc",
    "Sections":[
        {
            "name":"sec1",
            "Description":"desc1",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]    
        },
        {
            "name":"sec2",
            "Description":"desc2",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]     
        }
    ]
}