@host=https://localhost:7264
@hostId=4d775933-172d-422d-a2e2-3b13d86496c7
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MDg5OWFkZC1iZTdlLTQ3MGYtYmE0Mi0zYWQwYWVhODk0ZTYiLCJnaXZlbl9uYW1lIjoiQWxhIiwiZmFtaWx5X25hbWUiOiJLb3dhbHNrYSIsImp0aSI6Ijc4N2MzNGIwLTExZWYtNDZlZC05MzM1LTY2NmQ0N2M2YTAwNiIsImV4cCI6MTY3MjgwOTUxNiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9._lodxABS4-W792vX-QqTibPNrxasX1HblWDbj4_l04c

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"ala",
    "Description":"desc",
    "Sections":[
        {
            "name":"sec1",
            "Description":"desc1",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]    
        },
        {
            "name":"sec2",
            "Description":"desc2",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]     
        }
    ]
}