@host=https://localhost:7264
@hostId=4d775933-172d-422d-a2e2-3b13d86496c7
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTQ2OTkyYy1iNzk1LTRlYjgtOTFmYS05MjM4MjYwNjM3ZDMiLCJnaXZlbl9uYW1lIjoiQWxhIiwiZmFtaWx5X25hbWUiOiJLb3dhbHNrYSIsImp0aSI6IjI0YjZiZWM1LWNjZjMtNGE4NC1iODA3LWUzOTE1N2FmODMzNiIsImV4cCI6MTcyNzE1NzAzMCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.hbfE5TbwF5beIivfmBcirPa9ER_HPeqS1H8aGGPH26s

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":"ala",
    "Description":"desc",
    "Sections":[
        {
            "name":"sec1",
            "Description":"desc1",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]    
        },
        {
            "name":"sec2",
            "Description":"desc2",
            "Items":[
                {
                    "name":"item1",
                      "Description":"item1"     
                },
                {
                     "name":"item2",
                      "Description":"item2"  
                }
            ]     
        }
    ]
}